[workspace]
authors = ["Awenforever <king_wedo@163.com>"]
channels = ["conda-forge"]
name = "FlameHeight"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
opencv = ">=4.12.0,<5"
numpy = ">=2.2.6,<3"
matplotlib = ">=3.10.8,<4"
rich = ">=14.2.0,<15"
zstandard = ">=0.25.0,<0.26"
python-dotenv = ">=1.2.1,<2"
